Day 1 - 11, 14 ,16, 18, 15
Day 2 - 10, 22, 12, 15, 44
Day 3 - 42, 22, 11, 55, 33
Day 4 - 22, 33, 34, 22, 11

In [2]:
import numpy as np

In [11]:
twodArray = np.array([ [11, 14 ,16, 18, 15], [10, 22, 12, 15, 44], [42, 22, 11, 55, 33], [22, 33, 34, 22, 11]])
print(twodArray)

[[11 14 16 18 15]
 [10 22 12 15 44]
 [42 22 11 55 33]
 [22 33 34 22 11]]


In [18]:
# insert into 2D array
# insert  new column : axis = 1

new_array = np.insert(twodArray, 0,[[1,2,3,4]], axis=1)
print(new_array) 

[[ 1 11 14 16 18 15]
 [ 2 10 22 12 15 44]
 [ 3 42 22 11 55 33]
 [ 4 22 33 34 22 11]]


In [19]:
# insert into 2D array
# insert  new row : axis = 0

new_array = np.insert(new_array, 0,[[1,2,3,4,5,6]], axis=0)
print(new_array)

[[ 1  2  3  4  5  6]
 [ 1 11 14 16 18 15]
 [ 2 10 22 12 15 44]
 [ 3 42 22 11 55 33]
 [ 4 22 33 34 22 11]]


Traverse 2D Array

In [27]:
def traverse_2dArray(my_array):

    for i in range(rows_len):
        for j in range(col_len):
            print(my_array[i][j])

twodArray = np.array([[11, 14 ,16, 18, 15], [10, 22, 12, 15, 44], [42, 22, 11, 55, 33], [22, 33, 34, 22, 11]])
print(twodArray)
rows_len = len(twodArray)
col_len = len(twodArray[0])

traverse_2dArray(twodArray)



[[11 14 16 18 15]
 [10 22 12 15 44]
 [42 22 11 55 33]
 [22 33 34 22 11]]
11
14
16
18
15
10
22
12
15
44
42
22
11
55
33
22
33
34
22
11


In [33]:
# search in 2D Array

def search2DArray(my_array, value):

    for i in range(rows_len):
        for j in range(col_len):
            if my_array[i][j] == value:
                return f'The value is located at index {i} {j}'
    return 'Value not found'

twodArray = np.array([[11, 14 ,16, 18, 15], [10, 22, 12, 15, 44], [42, 22, 11, 55, 33], [22, 33, 34, 22, 11]])
print(twodArray)
rows_len = len(twodArray)
col_len = len(twodArray[0])

result = search2DArray(twodArray, 55)
print(result)



[[11 14 16 18 15]
 [10 22 12 15 44]
 [42 22 11 55 33]
 [22 33 34 22 11]]
The value is located at index 2 3


In [37]:
# Deletion in 2D Array

twodArray = np.array([[11, 14 ,16, 18, 15], [10, 22, 12, 15, 44], [42, 22, 11, 55, 33], [22, 33, 34, 22, 11]])
print(twodArray)
newArray1 = np.delete(twodArray, 0, axis = 0) # delete first row
print('=========================')
print(newArray1)
newArray2 = np.delete(twodArray, 0, axis = 1) # delete first column
print('=========================')
print(newArray2)


[[11 14 16 18 15]
 [10 22 12 15 44]
 [42 22 11 55 33]
 [22 33 34 22 11]]
[[10 22 12 15 44]
 [42 22 11 55 33]
 [22 33 34 22 11]]
[[14 16 18 15]
 [22 12 15 44]
 [22 11 55 33]
 [33 34 22 11]]
